
// Fetch HEADPHONEs
export const FETCH_HEADPHONES = 'FETCH_HEADPHONES';
export const FETCH_HEADPHONES_SUCCESS = 'FETCH_HEADPHONES_SUCCESS';
export const FETCH_HEADPHONES_FAILURE = 'FETCH_HEADPHONES_FAILURE';

// Add HEADPHONE
export const ADD_HEADPHONE = 'ADD_HEADPHONE';
export const ADD_HEADPHONE_SUCCESS = 'ADD_HEADPHONE_SUCCESS';
export const ADD_HEADPHONE_FAILURE = 'ADD_HEADPHONE_FAILURE';

// Update HEADPHONE
export const UPDATE_HEADPHONE = 'UPDATE_HEADPHONE';
export const UPDATE_HEADPHONE_SUCCESS = 'UPDATE_HEADPHONE_SUCCESS';
export const UPDATE_HEADPHONE_FAILURE = 'UPDATE_HEADPHONE_FAILURE';

// Delete HEADPHONE
export const DELETE_HEADPHONE = 'DELETE_HEADPHONE';
export const DELETE_HEADPHONE_SUCCESS = 'DELETE_HEADPHONE_SUCCESS';
export const DELETE_HEADPHONE_FAILURE = 'DELETE_HEADPHONE_FAILURE';

// Set form error
export const SET_FORM_ERROR = 'SET_FORM_ERROR';
export const RESET_FORM_ERROR = 'RESET_FORM_ERROR';

export const SET_HEADPHONES = 'SET_HEADPHONES';