
// Fetch KEYBOARDs
export const FETCH_KEYBOARDS = 'FETCH_KEYBOARDS';
export const FETCH_KEYBOARDS_SUCCESS = 'FETCH_KEYBOARDS_SUCCESS';
export const FETCH_KEYBOARDS_FAILURE = 'FETCH_KEYBOARDS_FAILURE';

// Add KEYBOARD
export const ADD_KEYBOARD = 'ADD_KEYBOARD';
export const ADD_KEYBOARD_SUCCESS = 'ADD_KEYBOARD_SUCCESS';
export const ADD_KEYBOARD_FAILURE = 'ADD_KEYBOARD_FAILURE';

// Update KEYBOARD
export const UPDATE_KEYBOARD = 'UPDATE_KEYBOARD';
export const UPDATE_KEYBOARD_SUCCESS = 'UPDATE_KEYBOARD_SUCCESS';
export const UPDATE_KEYBOARD_FAILURE = 'UPDATE_KEYBOARD_FAILURE';

// Delete KEYBOARD
export const DELETE_KEYBOARD = 'DELETE_KEYBOARD';
export const DELETE_KEYBOARD_SUCCESS = 'DELETE_KEYBOARD_SUCCESS';
export const DELETE_KEYBOARD_FAILURE = 'DELETE_KEYBOARD_FAILURE';

// Set form error
export const SET_FORM_ERROR = 'SET_FORM_ERROR';
export const RESET_FORM_ERROR = 'RESET_FORM_ERROR';

export const SET_KEYBOARDS = 'SET_KEYBOARDS';