
// Fetch MOUSEs
export const FETCH_MOUSES = 'FETCH_MOUSES';
export const FETCH_MOUSES_SUCCESS = 'FETCH_MOUSES_SUCCESS';
export const FETCH_MOUSES_FAILURE = 'FETCH_MOUSES_FAILURE';

// Add MOUSE
export const ADD_MOUSE = 'ADD_MOUSE';
export const ADD_MOUSE_SUCCESS = 'ADD_MOUSE_SUCCESS';
export const ADD_MOUSE_FAILURE = 'ADD_MOUSE_FAILURE';

// Update MOUSE
export const UPDATE_MOUSE = 'UPDATE_MOUSE';
export const UPDATE_MOUSE_SUCCESS = 'UPDATE_MOUSE_SUCCESS';
export const UPDATE_MOUSE_FAILURE = 'UPDATE_MOUSE_FAILURE';

// Delete MOUSE
export const DELETE_MOUSE = 'DELETE_MOUSE';
export const DELETE_MOUSE_SUCCESS = 'DELETE_MOUSE_SUCCESS';
export const DELETE_MOUSE_FAILURE = 'DELETE_MOUSE_FAILURE';

// Set form error
export const SET_FORM_ERROR = 'SET_FORM_ERROR';
export const RESET_FORM_ERROR = 'RESET_FORM_ERROR';

export const SET_MOUSES = 'SET_MOUSES';