
// Fetch LICENSEs
export const FETCH_LICENSES = 'FETCH_LICENSES';
export const FETCH_LICENSES_SUCCESS = 'FETCH_LICENSES_SUCCESS';
export const FETCH_LICENSES_FAILURE = 'FETCH_LICENSES_FAILURE';

// Add LICENSE
export const ADD_LICENSE = 'ADD_LICENSE';
export const ADD_LICENSE_SUCCESS = 'ADD_LICENSE_SUCCESS';
export const ADD_LICENSE_FAILURE = 'ADD_LICENSE_FAILURE';

// Update LICENSE
export const UPDATE_LICENSE = 'UPDATE_LICENSE';
export const UPDATE_LICENSE_SUCCESS = 'UPDATE_LICENSE_SUCCESS';
export const UPDATE_LICENSE_FAILURE = 'UPDATE_LICENSE_FAILURE';

// Delete LICENSE
export const DELETE_LICENSE = 'DELETE_LICENSE';
export const DELETE_LICENSE_SUCCESS = 'DELETE_LICENSE_SUCCESS';
export const DELETE_LICENSE_FAILURE = 'DELETE_LICENSE_FAILURE';

// Set form error
export const SET_FORM_ERROR = 'SET_FORM_ERROR';
export const RESET_FORM_ERROR = 'RESET_FORM_ERROR';

export const SET_LICENSES = 'SET_LICENSES';