
// Fetch LAPTOPs
export const FETCH_LAPTOPS = 'FETCH_LAPTOPS';
export const FETCH_LAPTOPS_SUCCESS = 'FETCH_LAPTOPS_SUCCESS';
export const FETCH_LAPTOPS_FAILURE = 'FETCH_LAPTOPS_FAILURE';

// Add LAPTOP
export const ADD_LAPTOP = 'ADD_LAPTOP';
export const ADD_LAPTOP_SUCCESS = 'ADD_LAPTOP_SUCCESS';
export const ADD_LAPTOP_FAILURE = 'ADD_LAPTOP_FAILURE';

// Update LAPTOP
export const UPDATE_LAPTOP = 'UPDATE_LAPTOP';
export const UPDATE_LAPTOP_SUCCESS = 'UPDATE_LAPTOP_SUCCESS';
export const UPDATE_LAPTOP_FAILURE = 'UPDATE_LAPTOP_FAILURE';

// Delete LAPTOP
export const DELETE_LAPTOP = 'DELETE_LAPTOP';
export const DELETE_LAPTOP_SUCCESS = 'DELETE_LAPTOP_SUCCESS';
export const DELETE_LAPTOP_FAILURE = 'DELETE_LAPTOP_FAILURE';

// Set form error
export const SET_FORM_ERROR = 'SET_FORM_ERROR';
export const RESET_FORM_ERROR = 'RESET_FORM_ERROR';

export const SET_LAPTOPS = 'SET_LAPTOPS';